DROP TABLE IF EXISTS `#__umva_tbllanguage`;

CREATE TABLE `#__umva_tbllanguage` (
  `lang_id` int(11) NOT NULL AUTO_INCREMENT,
  `lang_code` varchar(10) NOT NULL,
  `lang_name` varchar(50) NOT NULL,
  `is_translated` bool ,
  
  PRIMARY KEY (`lang_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;


INSERT INTO `#__umva_tbllanguage` (`lang_id`, `lang_code`, `lang_name`, `is_translated`) VALUES
(1,'en','english',1),
(2,'ne','nepali',1);


DROP TABLE IF EXISTS `#__umva_tbllangen`;

CREATE TABLE `#__umva_tbllangen` (
  `message_id` int(11) NOT NULL AUTO_INCREMENT,
  `translated_msg` text NOT NULL,
  PRIMARY KEY (`message_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8  AUTO_INCREMENT=1 ;

INSERT INTO `#__umva_tbllangen` (`message_id`, `translated_msg`) VALUES
(1, 'You gave an empty criteria'),
(2, 'Profile of %1% was saved'),
(3, 'Modifications has been saved'),
(4, 'Safes for user %1% have been created.'),
(5, 'User does not exist'),
(6, 'Enter the username of an existing UMVA user. This will make the initial safe(s) for his or her default account.'),
(7, 'UMVA ID'),
(8, 'Create'),
(9, 'Personal Info'),
(10, 'System Language'),
(11, 'My Speaking Language'),
(12, 'Bank Account'),
(13, 'Profession'),
(14, 'Country'),
(15, 'Region'),
(16, 'Place'),
(17, 'Phone'),
(18, 'Mobile'),
(19, 'Business Center'),
(20, 'Company'),
(21, 'Skype'),
(22, 'Website'),
(23, 'About Myself'),
(24, 'Sponsors'),
(25, 'Name'),
(26, 'Contract'),
(27, 'Save'),
(28, 'back'),
(29, 'Profile pictures'),
(30, 'Upload new photo'),
(31, 'Upload'),
(32, 'Upload new idcard photo'),
(33, 'Full name'),
(34, 'Address'),
(35, 'Email'),
(36, 'edit registration data'),
(37, 'edit personal data'),
(38, 'edit bank account'),
(39, 'Edit account pictures'),
(40, 'banks'),
(41, 'User does not not have a default account so you can not assing him to a bank'),
(42, 'Crop image'),
(43, 'submit'),
(44, 'Create Account'),
(45, 'User Search'),
(46, 'Registration Info for user %1%'),
(47, 'First Name'),
(48, 'Last Name'),
(49, 'ID Card Number'),
(50, 'E-mail'),
(51, 'Birthday'),
(52, 'Umva Foundation'),
(53, 'PICTURE'),
(54, 'Upload new picture'),
(55, 'Save new picture'),
(56, 'Delete picture'),
(57, '"Users found: %1%'),
(58, 'First name'),
(59, 'Last name'),
(60, 'Account'),
(61, 'Bank'),
(62, 'firstname'),
(63, 'lastname'),
(64, 'account'),
(65, 'Search'),
(66, 'System Error: %1%'),
(67, 'Hello %1% you are logged as receptionist!'),
(68, 'This field is required'),
(69, 'Bank is required'),
(70, 'Account number is required'),
(71, 'Account number is too short (2 characters minimum)'),
(72, 'Account number is too long (5 characters maximum)'),
(73, 'E-mail address is not valid'),
(74, 'E-mail address is too long'),
(75, 'Invalid date'),
(76, 'This field is too short (2 characters minimum)'),
(77, 'This field is too long (50 characters maximum)'),
(78, 'This field is too short (10 characters minimum)'),
(79, 'This field is too long (500 characters maximum)'),
(80, 'Booking done.'),
(81, 'Error %1%'),
(82, 'You provided empty criteria'),
(83, 'Date'),
(84, 'Account number'),
(85, 'Transaction ID'),
(86, 'Customer UMVA ID'),
(87, 'Family name'),
(88, 'Given name'),
(89, 'Previous balance'),
(90, 'Action'),
(91, 'Amount'),
(92, 'New Balance'),
(93, 'Operation description'),
(94, 'report'),
(95, 'Hello %1% you are logged as cashier!'),
(96, 'Cashier'),
(97, 'CUSTOMER'),
(98, 'Description'),
(99, 'Withdraw'),
(100, 'Deposit'),
(101, 'Withdraw from saving'),
(102, 'Loan'),
(103, 'Redeem debt'),
(104, 'To social capital'),
(105, 'T.I.P to current'),
(106, '%1% Booking Report'),
(107, 'No cashier account created yet'),
(108, 'No user account created yet'),
(109, 'Is this correct?'),
(110, 'yes'),
(111, 'cancel'),
(112, 'Please enter an integer'),
(113, 'The value must be at least one'),
(114, 'This field is too long (100 characters maximum)'),
(115, 'Bank number or bank are manadtory field.'),
(116, 'File containg more than 10% of invalids data or salaries data is uploaded.'),
(117, 'File containg more than 10% of invalids data or users data is uploaded.'),
(118, 'Failed users uploads. Check file and try again.'),
(119, 'The amount available in bank account is less than salaries uploads total amount.'),
(120, 'Account is'),
(121, '"Dear customer'),
(122, '"Regards'),
(123, 'File'),
(124, 'file has header'),
(125, 'Users file is required'),
(126, 'Head is required'),
(127, 'Not used.'),
(128, 'Salary file is required'),
(129, 'Head is not required'),
(130, 'File with users is required'),
(131, 'Employer'),
(132, 'Month'),
(133, 'Year'),
(134, 'Total amount'),
(135, 'Salaries file'),
(136, 'You must set employer.'),
(137, 'Month is required'),
(138, 'The salary of period was send.'),
(139, 'Year is required'),
(140, 'Total amount is required'),
(141, '"The total amount ""%value%"" is too short. It must be of %min_length% characters at least."'),
(142, '"The total amount ""%value%"" is too lenght. It must be less or equal to than %max_length% characters."'),
(143, '"The total amount ""%value%"" must be only digit characters."'),
(144, '"The total amount ""%value%"" is greater than available in bank account number:"'),
(145, 'Total amount is required 1'),
(146, 'Descriptiont number is required'),
(147, 'The account number is required'),
(148, '"The account number ""%value%"" is too short. It must be of %min_length% characters at least."'),
(149, '"The account number ""%value%"" is too lenght. It must be less or equal to than %max_length% characters."'),
(150, '"The account number ""%value%"" isn''t exist."'),
(151, 'The account number is required.'),
(152, 'Choose'),
(153, 'You must set column'),
(154, 'The users upload file is required.'),
(155, 'Users Upload'),
(156, '<<'),
(157, 'First'),
(158, '<'),
(159, 'Previous'),
(160, '>'),
(161, 'Next'),
(162, '>>'),
(163, 'Last'),
(164, '"[0] no result|[1] 1 result|(1'),
(165, 'Salary Upload'),
(166, 'Warning'),
(167, 'next'),
(168, 'Salary upload'),
(169, '"[0] 0 salary |[1] 1 salary |(1'),
(170, 'of'),
(171, 'from'),
(172, 'are succesfully uploaded from document csv'),
(173, 'Set types of fields'),
(174, 'At the left side choose filed type. At rightyoucan see small part of data from  your file.'),
(175, '"[0] 0 rows of data is invalid.|[1] 1 row of data is invalid.|(1'),
(176, '"[0] 0 rows of data is correct loaded.|[1] 1 row of data is correct loaded.|(1'),
(177, '1. Download the file with invalid data.'),
(178, '2. Correct invalit data.'),
(179, 'Download file'),
(180, '3. Upload the file again.'),
(181, '"[0] 0 user is.|[1] 1 user is.|(1'),
(182, 'succesfully uploaded from document csv'),
(183, 'Email is sending with performing registration.'),
(184, 'Receptionist don''t have bank'),
(185, 'unlocked'),
(186, 'locked'),
(187, 'Generate Report'),
(188, '%1% report'),
(189, 'from'),
(190, 'to'),
(191, 'Language is not valid'),
(192, 'Bad login or password'),
(193, 'Don''t have permission to this section!'),
(194, 'You cannot allow with this role'),
(195, 'UMVA Sign-in'),
(196, 'password'),
(197, 'role'),
(198, 'Login'),
(199, 'You have those roles:'),
(200, '%1% module'),
(201, 'Fill in UMVA ID'),
(202, 'Invalid characters in UMVA ID'),
(203, 'Fill in password'),
(204, 'Choose role'),
(205, 'Account charged'),
(206, 'Role %1% has been assignd to %2%'),
(207, 'User %1% already had the role assigned.'),
(208, 'Created account for this role.'),
(209, 'Created safe(s) for this role''s account.'),
(210, 'Enter username and amount. The current safe of this user will be charged.'),
(211, 'Charge'),
(212, 'Enter role for user %1%'),
(213, 'You are about to charge his/her account with:'),
(214, 'Are you Sure?'),
(215, 'Confirm'),
(216, 'Bank Booking'),
(217, 'Assing Role'),
(218, 'Mass upload'),
(219, 'Assign Role to a user'),
(220, 'Enter UVMA ID'),
(221, 'And Role'),
(222, 'Submit'),
(223, 'Hello %1% you are logged as administrator!'),
(224, 'Logout'),
(225, 'ASSIGN ROLE'),
(226, 'Assign Role'),
(227, 'MASS UPLOAD'),
(228, 'Salary Upload'),
(229, 'REPORTS'),
(230, 'Financial Booking Report'),
(231, 'Users Balances List'),
(232, 'PREDEFINED BOOKING'),
(233, 'List'),
(234, 'New Entry'),
(235, 'USER SEARCH'),
(236, 'User Balances Report'),
(237, 'User List'),
(238, 'Current Bank User List'),
(239, 'Welcome in UMVA administration panel'),
(240, 'No search criteria entered'),
(241, 'Enter the username of an existing UMVA user. This will make the initial safe(s) for the default account.'),
(242, 'Upload new id-card scan'),
(243, 'UMVA Organisation'),
(244, 'User verification'),
(245, 'Error. More than 10% of file data is invalid.'),
(246, 'User upload init failed.'),
(247, 'empty_'),
(248, 'Dear customer'),
(249, 'Your account was created. You can login to your profile using following UMVA ID and password:'),
(250, 'Password'),
(251, 'Remember to change your password.'),
(252, 'Regards'),
(253, 'UMVA Team'),
(254, 'Invalid value'),
(255, 'Invalid bank code'),
(256, 'Invalid given name'),
(257, 'Invalid family name'),
(258, 'Invalid address country'),
(259, 'Invalid phone number'),
(260, 'Invalid mobile number'),
(261, 'Invalid UMVA organization'),
(262, 'Invalid UMVA business center'),
(263, 'Invalid current safe value'),
(264, 'Invalid saving safe value'),
(265, 'Invalid loan safe value'),
(266, 'Invalid transition safe'),
(267, 'Invalid social capital safe value'),
(268, 'Invalid website url'),
(269, 'Invalid email'),
(270, 'Invalid service level'),
(271, 'Bank account exists'),
(272, 'User is duplicate'),
(273, 'Invalid Id.'),
(274, 'Users not sent.'),
(275, 'Transaction failed'),
(276, 'Invalid data'),
(277, 'The account number does not exist.'),
(278, 'The characters are invalid.'),
(279, 'The company does not exist.'),
(280, 'The salary of period was sent.'),
(281, '"The total amount ""%value%"" is too long. It must be less or equal to %max_length% characters."'),
(282, 'Description number is required'),
(283, '"The account number ""%value%"" is too long. It must be less or equal to %max_length% characters."'),
(284, 'Total of safes'),
(285, 'Upload again'),
(286, '"[0] no results|[1] 1 result|(1'),
(287, 'Total amount of salaries is greater than settings on step one:'),
(288, 'Receptionist is not associated with a bank.'),
(289, 'Letter'),
(290, 'You do not have credentials to access this section!'),
(291, 'language'),
(292, 'Enter UMVA ID'),
(293, 'Enter Password'),
(294, 'Bank booking was not performed. Recipient account for the selected role does not exist. Please create it first (via ''assign role'' as administrator or ''create account'' as receptionist).'),
(295, 'Predefined Booking Entry Deleted'),
(296, 'You cannot remove the main booking'),
(297, 'Error'),
(298, 'error in deleting operation'),
(299, 'predefined booking deleted'),
(300, 'Role %1% has been assigned to %2%'),
(301, 'Edit Entry for %1%'),
(302, 'You chose to edit this entry of booking:'),
(303, 'predefined Booking'),
(304, 'This field can be empty only in the root entry.'),
(305, 'Predefined Booking Entry for id %1% was deleted'),
(306, 'Predefined booking list'),
(307, '%1%'),
(308, 'User from'),
(309, 'User to'),
(310, 'Operations'),
(311, '#EMPTY#'),
(312, 'edit'),
(313, 'Create New Entry'),
(314, 'Salary Upload From %1% %2% %3%'),
(315, 'Account was created.'),
(316, 'Download confirmation user upload'),
(317, 'Current Bank User Fee List'),
(318, 'Add'),
(319, 'Upload new signature scan'),
(320, 'Search result'),
(321, 'Changes renew status to %1%'),
(322, 'Changing renew status failed'),
(323, 'Safe Overview'),
(324, 'Disable renew'),
(325, 'Enable renew'),
(326, 'Salary of %2%-%3%'),
(327, 'Safe Booking List'),
(328, 'Safe'),
(329, 'Start Of The Day (cashier)'),
(330, 'Selected amount doesn''t match the sum of amounts for the cashiers.'),
(331, 'Master safe user doesn''t have appropriate account.'),
(332, 'Master safe user doesn''t have appropriate safe.'),
(333, 'Master safe user error.'),
(334, 'Cashier doesn''t have account.'),
(335, 'Cashier doesn''t have current safe.'),
(336, 'Cashier user error.'),
(337, 'General ledger error.'),
(338, 'Cashier''s safe balacnce is too low.'),
(339, 'Bank booking was not performed. Recipient account for the selected role does not exist. Please create it first (via '' role'' as administrator or ''create account'' as receptionist).'),
(340, 'Predefined Booking Entry saved'),
(341, 'General Ledger account from does not exist.'),
(342, 'General Ledger account from exist only for banks: %bank_code%.'),
(343, 'General Ledger account from does not exist for banks: %bank_code%.'),
(344, 'General Ledger account to does not exist.'),
(345, 'General Ledger account to exist only for banks: %bank_code%.'),
(346, 'General Ledger account to does not exist for banks: %bank_code%.'),
(347, 'Unknown error'),
(348, 'Ballance is to less.'),
(349, 'You chose to set this entry of booking:'),
(350, 'End of the Day (Cashier)'),
(351, 'Choose Cashier and count cash for them'),
(352, 'Count Cash'),
(353, 'End'),
(354, 'You have decided to start with %%administrator%% master safe.'),
(355, 'face value'),
(356, 'quantity'),
(357, 'total'),
(358, 'Print'),
(359, 'New'),
(360, 'Old'),
(361, 'Start of the Day (Cashier)'),
(362, '"You''ve decided to start with %value% RWF'),
(363, '"Day has been ended with %value% RWF'),
(364, 'Run'),
(365, 'Day has been started. Booked %%amount%% RWF from %%administrator%% to bank.'),
(366, '"Day has been started with %value% RWF'),
(367, 'General Ledger group'),
(368, 'End Of The Day (cashier)'),
(369, 'Start Of The Day (adm)'),
(370, 'Create Super Admin Report'),
(371, 'Dutch'),
(372, 'English'),
(373, 'French'),
(374, 'Russian'),
(375, 'Kinyarwanda'),
(376, 'Swahili'),
(377, 'Chinese'),
(378, 'Gender'),
(379, 'Hello %1%. You are logged in as receptionist!'),
(380, 'Customer'),
(381, 'Cashier''s current safes'),
(382, 'The report cannot be handled.'),
(383, 'The code of value does not correct.'),
(384, 'The user exist in salary upload.'),
(385, 'Total amount of salaries is lesser than settings on step one:'),
(386, 'Error with creating report.'),
(387, 'Value'),
(388, 'Grouping method'),
(389, 'All'),
(390, 'Group by user'),
(391, 'User totals'),
(392, 'Cashier doesn''t have general ledger account.'),
(393, 'Cashier assigned to different bank.'),
(394, 'Cashier is assigned to many accounts of general ledger.'),
(395, 'Error. Predefinedbooking was not saved.'),
(396, 'Error deleting predefined booking entry.'),
(397, 'Predefined booking entry deleted.'),
(398, 'Predefined booking create'),
(399, 'Add booking'),
(400, 'Account from'),
(401, 'Account to'),
(402, 'Operation code'),
(403, 'Bank does not exists'),
(404, 'Bank cannot be changed'),
(405, 'User is already associated with another bank then the selected one'),
(406, 'GL account has not been created yet.'),
(407, 'GL chart of account has not been created yet.'),
(408, 'The account of general ledger shouldn''t be assgin'),
(409, 'The cashier has been already assigned to account of general ledger'),
(410, 'Value type'),
(411, 'The value type of bank is required.'),
(412, 'User associated with another bank'),
(413, 'User has created already account'),
(414, 'The account of general ledger of cashier is not assigned'),
(415, 'Safe does not exists'),
(416, 'Invalid amount'),
(417, 'Cashier assigned to too many genral ledger accounts.'),
(418, 'The reports name is required.'),
(419, 'The limit is required.'),
(420, 'The offset is required.'),
(421, 'Invalid predefined booking id'),
(422, 'Invalid predefined booking entry id'),
(423, 'Amount must be greater than 0'),
(424, 'Invalid description'),
(425, 'Invalid operation'),
(426, 'Invalid valid for'),
(427, 'Invalid valid unit'),
(428, 'Invalid value type'),
(429, 'Invalid requried predefined booking id'),
(430, 'Missing root entry values'),
(431, 'Bank account from cannot be set for root entry'),
(432, 'Empty bank account from'),
(433, 'Tried to modify predefined booking id of existing predefined booking id'),
(434, 'Tried to modify readonly fields'),
(435, 'Sum of children amounts cannot be higher than root''s'),
(436, 'Bank account to cannot be empty'),
(437, 'Number of banks is required'),
(438, '"Number of banks ""%value%"" is too short. It must be of %min_length% characters at least."'),
(439, '"Number of banks ""%value%"" is too long. It must be less or equal to %max_length% characters."'),
(440, 'Invalid number'),
(441, 'You must set cashier numbers field'),
(442, 'Must be bigger than 0'),
(443, 'Value invalid'),
(444, 'Amount is not valid'),
(445, 'General error'),
(446, 'booking exists'),
(447, 'User not exist'),
(448, 'You cannot move root entry'),
(449, 'Safe of user not exists'),
(450, 'Invalid period'),
(451, 'User is null'),
(452, 'Account not exists'),
(453, 'The amount is greater than available in root booking and defined in entries.'),
(454, 'Booking not valid'),
(455, 'Account does not exsits'),
(456, 'Bank account not exists'),
(457, 'Administrator UMVA ID'),
(458, 'Number of banks'),
(459, 'Bank does not exist.'),
(460, 'Master Safe UMVA ID'),
(461, 'Number of Cashiers'),
(462, 'Amount to start with'),
(463, 'The code of gender is not correct.'),
(464, 'Payments'),
(465, 'Number of payments'),
(466, 'Status'),
(467, 'Actions'),
(468, 'Uploaded'),
(469, 'Pending'),
(470, 'View'),
(471, 'Upload payment'),
(472, 'Choose Language'),
(473, 'Bank account for UMVA ID'),
(474, 'Account of user has not been created yet.'),
(475, 'Modifications were not saved.'),
(476, 'Receptionist have to be assigned to a bank.'),
(477, 'Account already created for this UMVA ID'),
(478, 'Receptionist'),
(479, 'Administrator'),
(480, 'General Ledger Booking'),
(481, 'Debit'),
(482, 'Credit'),
(483, 'Code'),
(484, 'Details'),
(485, 'Cashier Account'),
(486, 'Customer Account'),
(487, 'Decimal fraction is not allowed.'),
(488, 'Cannot redeem bigger amount than amount which is in the loan safe.'),
(489, 'ID Cashier'),
(490, 'Client Account Number'),
(491, 'Client ID'),
(492, 'Previous Balance'),
(493, 'Signature'),
(494, 'System charge'),
(495, 'Converted amount'),
(496, 'Start of the Day (Administrator)'),
(497, 'Root predefined booking entry has been created.'),
(498, 'Root predefined booking entry has been edited.'),
(499, 'Predefined booking entry has been created.'),
(500, 'Predefined booking entry has been edited.'),
(501, 'GL Account number'),
(502, 'Value type is required.'),
(503, 'Money Arrived'),
(504, 'Date from'),
(505, 'Date to'),
(506, 'Membership - level 1'),
(507, 'Membership - level 2'),
(508, 'Other'),
(509, 'Image file is required'),
(510, 'Name is required'),
(511, 'Day'),
(512, 'Requires'),
(513, 'BANK %1%'),
(514, 'Amount %1%'),
(515, 'Old Amount %1%'),
(516, 'Bank account %1%'),
(517, '"Data processing'),
(518, 'loading'),
(519, 'The file is unavailable.'),
(520, 'User file is required'),
(521, 'The mandatory entries aren''t set.'),
(522, 'UMVA Registration');

DROP TABLE IF EXISTS `#__umva_tbllangne`;

CREATE TABLE `#__umva_tbllangne` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `message_id` int(11) NOT NULL,
  `translated_msg` text NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;




